### PR TITLE
More precise BeatTimeline.get_times_by_measure

### PR DESCRIPTION
**Pull request by FelipeDefensor**
Take beat times into consideration in BeatTimeline.get_times_by_measure.

### CODE REVIEW

**Comment by FelipeDefensor** [comment]
@azfoo hold up a bit on this review, I just remembered something.

**Comment by FelipeDefensor** [comment]
Done, you can go ahead.

**Comment by azfoo** [comment]
Sorry I forgot about the existence of this and accidentally did work for this in the mxl branch (which I separated out to 
[this branch](https://github.com/azfoo/TiLiA/tree/better-beat). Haven't written tests for it, but this creates/uses a lookup table which would be useful for quick conversion to score positions in the mxl-parser. (There's definitely room to make the lookup table smaller if necessary.) There shouldn't be an issue with measure zero and the last measure in this one, except you'll need to put in an extra beat at the end of the last measure (belonging to last + 1 measure) to end things off properly.

**Comment by FelipeDefensor** [comment]
> Sorry I forgot about the existence of this and accidentally did work for this in the mxl branch (which I separated out to [this branch](https://github.com/azfoo/TiLiA/tree/better-beat). Haven't written tests for it, but this creates/uses a lookup table which would be useful for quick conversion to score positions in the mxl-parser. (There's definitely room to make the lookup table smaller if necessary.) There shouldn't be an issue with measure zero and the last measure in this one, except you'll need to put in an extra beat at the end of the last measure (belonging to last + 1 measure) to end things off properly.

No problem. So I imagine you version is more performant. Can we use the tests I wrote also in that branch?

**Comment by azfoo** [comment]
> No problem. So I imagine you version is more performant. Can we use the tests I wrote also in that branch?
Tests added and passed. 
I removed measure zero because it shouldn't be an issue if the user manually adds in a measure 0. Having measure zero without an actual user-defined start point would be too arbitrary.

**Comment by FelipeDefensor** [comment]
> > No problem. So I imagine you version is more performant. Can we use the tests I wrote also in that branch?
> > Tests added and passed.
> 
> I removed measure zero because it shouldn't be an issue if the user manually adds in a measure 0. Having measure zero without an actual user-defined start point would be too arbitrary.

Not sure I agree. I think most users will be surprised that anacrusis don't get magically imported, even with no explicit setup on their part, but I'm fine with not doing that for now and waiting for user feedback.

**Comment by FelipeDefensor** [comment]
Closing this in favor of the more performant version mentioned above.

**Pull request closed without merging**
