### PR TITLE
Wheel Events

### LINKED ISSUE #141: Zooming is causing vertical scrolling of timeline area
This is only observable, of course, when the timelines are "taller" than the visible timeline area, which causes a vertical scrollbar to appear.

### PR DESCRIPTION
**Pull request by azfoo**
closes #141 
Fixes accidental scroll on zoom
Added horizontal and vertical zooming through modifiers

### CODE REVIEW

**Comment by azfoo** [comment]
It's mostly for you to have a play around and see what you think. 
Vertical scrolling might not be the most useful feature but horizontal scrolling should be handy considering most of the data in the app is along the x-axis. 
Standardised wheel events might be more intuitive for the first-time user, and zooming is still only two clicks away either by the shortcut or the view buttons.

**Comment by FelipeDefensor** [comment]
I'm still getting the extra vertical scrolling. Maybe some Qt default?


https://github.com/TimeLineAnnotator/desktop/assets/87732202/0dcdcc3e-25a4-47ed-8c2d-32020389c386

I like the Shift+Wheel for horizontal scrolling!

I'm still not sure about the horizontal zooming, but good point about it still being available farily easily. I was thinking that eventually we need to add one of those percentage and slider interfaces for zooming that most document viewers have ...

image

... so what about we postpone changing the sortcuts until then?

**Comment by azfoo** [comment]
that should fix it - though it might have accidentally fixed something that was meant for the next version too.

**Comment by azfoo** [comment]
not quite commented out, just stored in a function that is never called. switching over will just involve changing/replacing function names.

**Comment by FelipeDefensor** [comment]
> not quite commented out, just stored in a function that is never called. switching over will just involve changing/replacing function names.

That's even better. Feel free to merge.

**Pull request merged**
