### PR TITLE
fix: args typo

### PR DESCRIPTION
**Pull request by azfoo**
was causing pdf & beat to not load

### CODE REVIEW

**Review by FelipeDefensor — APPROVED** [review]
Glad you caught this right away. Merge this ASAP.

**Comment by FelipeDefensor** [comment]
Important lessons to learn here:
1. Using `Serve` to mock user input may conceal bugs. We should find a way to simulate user interactions more faithfully, in those cases. Using `QDialog.show` instead of `QDialog.exec` with `qtbot` might be the way, as we have previsously discussed.
2. While we don't have that in place, we should always test things manually at least once before pushing changes.

**Comment by azfoo** [comment]
That was a big oops. Should have caught this when I tested.

**Comment by FelipeDefensor** [comment]
> That was a big oops. Should have caught this when I tested.

Big oops for both of us, I should never had pushed it without testing it myself.

**Pull request merged**
