### PR TITLE
Fix double clicks on most timeline UI elements initiating drag

### PR DESCRIPTION
**Pull request by FelipeDefensor**

### CODE REVIEW

**Comment by FelipeDefensor** [comment]
Fixes #158

**Comment by azfoo** [comment]
I was trying to abstract this into the super class since there is a lot of "same" code - the app still works but the test fails. That could be a potential fix for the future.

**Comment by FelipeDefensor** [comment]
> I was trying to abstract this into the super class since there is a lot of "same" code - the app still works but the test fails. That could be a potential fix for the future.

I was sure that I left a comment about that on the commit message body, but I can't find it. Yes, there is a lot of duplication going on. My first idea was to use a mixin since not all TimelineUIElement subclasses are draggable but abstracting into the super class might also work. I have created an issue draft in the project for this refactor.

**Review by azfoo — APPROVED** [review]
fixed!

**Pull request merged**
