### PR TITLE
feat: add save metadata buttons

### LINKED ISSUE #182: Missing a save button in the metadata window
Currently, the only way to save is to confirm the dialog when trying to close, which is counterintuitive. We could without the save button if changes were autosaved, but hen we would need a discard button.

### PR DESCRIPTION
**Pull request by azfoo**
closes #182

### CODE REVIEW

**Review by FelipeDefensor — APPROVED** [review]
All good!

**Comment by FelipeDefensor** [comment]
So, now that there's no exit confirmation dialog and we need to apply the changes, the initial focus on the cancel button is an issue. If we type into any field and press Enter hoping that it would apply the changes or take us to the next field, it actually closes the window immediately without saving.

I think we need a confirmation for discarding changes. Additionally, it might be a good idea to remove the focus from the cancel button.

**Comment by azfoo** [comment]
How about putting the confirm close back onto the close event and leaving the focus on cancel? (I think the focus on cancel is set by the os by default). That way even if you accidentally press cancel, you'll still have to go through another dialog before you actually close the window.

**Comment by FelipeDefensor** [comment]
> How about putting the confirm close back onto the close event and leaving the focus on cancel? (I think the focus on cancel is set by the os by default). That way even if you accidentally press cancel, you'll still have to go through another dialog before you actually close the window.

Yes, that works!

**Pull request merged**
