### PR TITLE
fix cli

### PR DESCRIPTION
**Pull request by azfoo**

### CODE REVIEW

**Comment by azfoo** [comment]
probably fixed. requires further testing but is working now.

**Comment by FelipeDefensor** [comment]
Good job! I have quickly tested it and everything seems to be working, apart from the "load-media" command. I will commit a fix later today.

**Review by FelipeDefensor — CHANGES_REQUESTED** [review]
My last commits implement Player instances for the CLI to fix the 'load-media' command. In that case, do we still need to serve the media path from the App class? If not, I think it's a better idea to go back to serving from Player, as that has been tested manually previously.

Apart from that, it seems like we have got our CLI back. Nice! I have not tested it thorougly, but we can do that manually while preparing the analyses for the TISMIR article.

**Comment by azfoo** [comment]
> My last commits implement Player instances for the CLI to fix the 'load-media' command. In that case, do we still need to serve the media path from the App class? If not, I think it's a better idea to go back to serving from Player, as that has been tested manually previously.
> 
Seems to work now with the previous method. I've updated and pushed things back up now.

**Review by FelipeDefensor — APPROVED** [review]
Looks good to me.

**Pull request merged**
